CREATE PROCEDURE [dbo].[sp_InsertTag]
	@Id int = 0,
	@Text nvarchar(50)
AS
SET TRANSACTION ISOLATION LEVEL SERIALIZABLE
BEGIN TRANSACTION
	SELECT @Id = Id FROM Tags WHERE Text = @Text
	IF @Id = 0
	BEGIN
		INSERT INTO Tags (Text) VALUES(@Text)
		SELECT @Id = SCOPE_IDENTITY()
	END
	SELECT @Id
COMMIT TRANSACTION
